# Generated by Django 2.1.5 on 2019-01-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=40, unique=True),
        ),
    ]
