# Generated by Django 2.2 on 2020-05-13 17:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200512_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 13, 17, 34, 2, 507301, tzinfo=utc)),
        ),
    ]
