# Generated by Django 2.1.5 on 2019-01-27 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190127_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 27, 14, 18, 14, 356605)),
        ),
    ]
