# Generated by Django 3.0.6 on 2020-05-14 08:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200513_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 14, 8, 45, 45, 696649, tzinfo=utc)),
        ),
    ]
