# Generated by Django 2.1.5 on 2019-01-27 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190127_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 27, 15, 5, 46, 127828)),
        ),
    ]
