# Generated by Django 2.1.5 on 2019-01-27 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20190127_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 27, 15, 8, 23, 430762)),
        ),
    ]
