# Generated by Django 2.2 on 2020-05-04 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20190127_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 4, 23, 32, 59, 43985)),
        ),
    ]
