# Generated by Django 2.2.8 on 2020-05-05 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200504_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 5, 12, 47, 50, 74352)),
        ),
    ]
